### ISSUE TITLE
Laravel5.3中request->header

### ISSUE THREAD

**Issue by zhangmazi** [chongyi/swoole-laravel-framework#2]
问题：拿不到host ，在做route()函数时，发现获取到的是错误的http域名
背景：nginx+swoole server 配置模式。 其中nginx负责处理静态文件。采用Laravel5.3

**Comment by zhangmazi** [comment]
刚刚试了最新Laravel5.2原版，纯swoole，没有nginx反代。 依然是拿不到host，无法正常route()函数

**Comment by zhangmazi** [comment]
我已经解决了。
因为你的代码composer对laravel版本5.3版不支持。所以不能fork提供merge request了。
下面的是解决方案
修改文件：src/Http/Request.php
修改行:53行 （`php $files   = isset($request->files) ? $request->files : [];`）下面
增加代码

``` php
 /**
         * 把headers内容塞入$server
         * @author ninja911<ninja911@qq.com>
         * @date 2016.09.13  14:28
         */
        if (is_array($request->header)) {
            foreach ($request->header as $k => $v) {
                $key = 'HTTP_' . strtoupper(str_replace('-', '_', $k));
                $server[$key] = $v;
            }
        }
```

**Comment by chongyi** [comment]
可以改对 composer 的限制，不过需要另行分支
