### ISSUE TITLE
该升级一下了，swoole 1.9版本的，composer安装不了

### ISSUE THREAD

**Issue by yangzhipeng** [chongyi/swoole-laravel-framework#5]
[InvalidArgumentException]                                           
  Could not find package chongyi/swoole-laravel-framework at any vers  
  ion for your minimum-stability (stable). Check the package spelling  
   or your minimum-stability

Problem 1
    - Installation request for chongyi/swoole-laravel-framework dev-master -> satisfiable by chongyi/swoole-laravel-framework[dev-master].
    - chongyi/swoole-laravel-framework dev-master requires ext-swoole ~1.8.1 -> the requested PHP extension swoole has the wrong version (1.9.14) installed.

**Comment by chongyi** [comment]
现在主要维护  `chongyi/keeper` 这个项目，也是一个基于 swoole 的开发脚手架，仍会提供对 Laravel 的支持，但是改动就比较多了。

因为当前这个坑比较多（主要集中在变量污染问题），随着版本迭代升级困难，现在 **`暂时`** 停止维护。如果有定制需求可以 fork 一份。
